---
- name: Setup pre-reqs and base packages for Openshift in Footloose
  hosts: all
  gather_facts: false

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
    openshift_client_tools: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    oc_config_dir: /openshift.local.clusterup
    public_hostname: 127.0.0.1.nip.io
    cert_dir: /root/certs
    additional_ips: '{{public_hostname}},172.17.0.2'

  pre_tasks:

  - name: Check if Footloose is installed
    shell: command -v footloose >/dev/null 2>&1
    register: footloose_installed
    ignore_errors: yes
    failed_when: false
    delegate_to: 127.0.0.1
    tags:
      - local
      - base
      - step1

  - name: Footloose installed
    fail:
      msg: "Footloose is not installed. Check https://github.com/weaveworks/footloose for instructions."
    delegate_to: 127.0.0.1
    when: footloose_installed is defined and footloose_installed.rc != 0
    tags:
      - local
      - base
      - step1

  - name: Exit playbook
    meta: end_play
    delegate_to: 127.0.0.1
    when: footloose_installed is defined and footloose_installed.rc != 0
    tags:
      - local
      - base
      - step1

  - name: Create Footloose container VMs
    command: footloose create
    delegate_to: 127.0.0.1
    tags:
      - local
      - base
      - step1

  - name: Install python2 for Ansible (Centos)
    raw: test -e /usr/bin/python || (yum -y update && yum install -y python) || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when: output.stdout != ""
    tags:
      - base
      - step1

  - name: Gathering Facts
    setup:
    tags:
      - base
      - step1
  tasks:

  - name: Get docker container IP
    command: 'docker inspect {{inventory_hostname}} -f {% raw %}"{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"{% endraw %}'
    register: container_ip
    delegate_to: 127.0.0.1
    tags:
      - base
      - local
      - step1

  - name: Upgrade all packages
    package:
      name: "*"
      state: latest
    tags:
      - base
      - step1

  - name: Install dnsmasq
    package:
      name:
      - dnsmasq
      state: latest
    tags:
      - base
      - step1

  - name: Configure dnsmasq
    copy:
      dest: "/etc/dnsmasq.conf"
      content: |
        domain-needed
        bogus-priv
        listen-address=127.0.0.1
        listen-address={{container_ip.stdout}}
        bind-interfaces
        server=1.1.1.1
        server=8.8.8.8
        address=/{{public_hostname}}/{{container_ip.stdout}}
      mode: 0644
    notify: restart dnsmasq
    tags:
      - base
      - step1

  - name: Ensure old versions of Docker are not installed.
    package:
      name:
      - docker
      - docker-common
      - docker-engine
      state: absent
    tags:
      - step1

  - name: Add Docker GPG key.
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present
    tags:
      - step1

  - name: Add Docker repository.
    get_url:
      url: "{{ docker_yum_repo_url }}"
      dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
      owner: root
      group: root
      mode: 0644
    tags:
      - step1

  - name: Install Docker.
    package:
      name: "{{ docker_package }}"
      state: present
    notify: restart docker
    tags:
      - step1

  - name: Ensure services are started and enabled at boot.
    service:
      name: '{{item}}'
      state: started
      enabled: true
    with_items:
      - docker
      - dnsmasq
    tags:
      - step1

  - name: Creates Docker directory
    file:
      path: /etc/docker
      state: directory
    tags:
      - step1

  - name: Configure Docker insecure registry
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
          "insecure-registries": [
            "172.17.0.0/16",
            "172.30.0.0/16"
          ]
        }
      mode: 0644
    notify: restart docker
    tags:
      - step1

  - name: Flush handlers to restart Docker
    meta: flush_handlers
    tags:
      - step1

  - name: Check if oc binary exists
    stat:
      path: /usr/local/bin/oc
    register: oc
    tags:
      - step1

  - name: Download and unpack OpenShift utility
    unarchive:
      src: "{{ openshift_client_tools }}"
      dest: /usr/local/bin
      remote_src: yes
      extra_opts: [--strip-components=1]
    when: oc.stat.executable is not defined
    tags:
      - step1

  - name: Create startup script
    copy:
      dest: "/root/oc-up.sh"
      content: |
        #!/usr/bin/env bash
        oc cluster up --skip-registry-check=true --public-hostname {{public_hostname}} --routing-suffix {{public_hostname}} --base-dir={{oc_config_dir}}
      mode: 0744
    tags:
      - step1

  - name: Generate cluster config
    command: "oc cluster up --skip-registry-check=true --public-hostname {{public_hostname}} --routing-suffix {{public_hostname}} --base-dir={{oc_config_dir}} --write-config=true"
    tags:
      - step1

  - name: Generate and replace certificates
    include_tasks: certificates.yml
    tags:
      - step1

  - name: Start the cluster
    command: "$HOME/oc-up.sh"
    register: cluster_up
    tags:
      - step2

  - name: Add optional features
    command: "oc cluster add automation-service-broker service-catalog template-service-broker --base-dir=/{{oc_config_dir}}"
    tags:
      - step2

  - name: Login into cluster
    command: "oc login -u system:admin"
    tags:
      - step2

  - name: Add cluster-admin permissions to admin user
    command: "oc adm policy add-cluster-role-to-user cluster-admin admin"
    tags:
      - step2

  - name: Label localhost node as master
    command: "oc label node localhost node-role.kubernetes.io/master= --overwrite"
    tags:
      - step2

  - name: Change upstream DNS config
    lineinfile:
      path: '{{oc_config_dir}}/kubedns/node-config.yaml'
      regexp: '^dnsNameservers:'
      line: 'dnsNameservers: ["{{container_ip.stdout}}:53"]'
    tags:
      - step2

  - name: Restart DNS pod after change
    command: "oc get pods -n kube-dns -o name | xargs oc delete -n kube-dns"
    tags:
      - step2

  - name: Cluster login info
    debug:
      msg:
        - "Cluster Login info:"
        - "{{ cluster_up  | regex_replace('\\n', '\n') }}"
    tags:
      - step2

  - name: Fetch config file
    fetch:
      src: /openshift.local.clusterup/kube-apiserver/admin.kubeconfig
      dest: ./openshift-config
      flat: yes
    tags:
      - config
      - info
      - step2

  - name: Openshift config file
    debug:
      msg:
        - "The cluster config has been downloaded into ./openshift-config \n
          Copy it to your $HOME/.config with: \n
          cp openshift-config $HOME/.kube/config \n
           \n
          Open https://{{public_hostname}}:8443/console to access the console. \n
           \n
          footloose ssh root@node0"
    tags:
      - config
      - info
      - step2

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted

    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
