---
- name: Setup pre-reqs and base packages for Openshift in Footloose
  hosts: all
  gather_facts: false

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
    openshift_client_tools: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz

  pre_tasks:

  - name: Check if Footloose is installed
    shell: command -v footloose >/dev/null 2>&1
    register: footloose_installed
    ignore_errors: yes
    failed_when: false
    delegate_to: 127.0.0.1
    tags:
      - local
      - base

  - name: Footloose installed
    fail:
      msg: "Footloose is not installed. Check https://github.com/weaveworks/footloose for instructions."
    delegate_to: 127.0.0.1
    when: footloose_installed is defined and footloose_installed.rc != 0
    tags:
      - local
      - base

  - name: Exit playbook
    meta: end_play
    delegate_to: 127.0.0.1
    when: footloose_installed is defined and footloose_installed.rc != 0
    tags:
      - local
      - base

  - name: Create Footloose container VMs
    command: footloose create
    delegate_to: 127.0.0.1
    tags:
      - local
      - base

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python2.7 python-minimal python-setuptools)"
    register: output
    changed_when: output.stdout != ""

  - name: Gathering Facts
    setup:

  tasks:

  - name: Upgrade all packages
    package:
      name: "*"
      state: latest

  - name: Ensure old versions of Docker are not installed.
    package:
      name:
      - docker
      - docker-common
      - docker-engine
      state: absent

  - name: Add Docker GPG key.
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present

  - name: Add Docker repository.
    get_url:
      url: "{{ docker_yum_repo_url }}"
      dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
      owner: root
      group: root
      mode: 0644

  - name: Install Docker.
    package:
      name: "{{ docker_package }}"
      state: present
    notify: restart docker

  - name: Ensure Docker is started and enabled at boot.
    service:
      name: docker
      state: started
      enabled: true

  - name: Ensure handlers are notified now to avoid firewall conflicts.
    meta: flush_handlers

  - name: Creates Docker directory
    file:
      path: /etc/docker
      state: directory

  - name: Configure Docker insecure registry
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
          "insecure-registries": [
            "172.17.0.0/16",
            "172.30.0.0/16"
          ]
        }
      mode: 0644
    notify: restart docker

  - name: Flush handlers to restart Docker
    meta: flush_handlers

  - name: Download and unpack OpenShift utility
    unarchive:
      src: "{{ openshift_client_tools }}"
      dest: /usr/local/bin
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Create startup script
    copy:
      dest: "/root/oc-up.sh"
      content: |
        #!/usr/bin/env bash
        oc cluster up --skip-registry-check=true --public-hostname=127.0.0.1.nip.io
      mode: 0744

  - name: Start the cluster
    command: "$HOME/oc-up.sh"
    register: cluster_up

  - name: Add optional features
    command: "oc cluster add automation-service-broker service-catalog template-service-broker"

  - name: Login into cluster
    command: "oc login -u system:admin"

  - name: Add cluster-admin permissions to admin user
    command: "oc adm policy add-cluster-role-to-user cluster-admin admin"

  - name: Cluster login info
    debug:
      msg:
        - "Cluster Login info:"
        - "{{ cluster_up  | regex_replace('\\n', '\n') }}"

  - name: Fetch config file
    fetch:
      src: ~/.kube/config
      dest: ./openshift-config
      flat: yes
    tags:
      - config
      - info

  - name: Openshift config file
    debug:
      msg:
        - "The cluster config has been downloaded into ./openshift-config \n
          Copy it to your $HOME/.config with: \n
          cp openshift-config $HOME/.kube/config \n
           \n
          Open https://127.0.0.1.nip.io:8443/console to access the console. \n
           \n
          footloose ssh root@node0"
    tags:
      - config
      - info

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
